######################################################################
# Automatically generated by qmake (3.0) Wed Apr 20 06:09:48 2016
######################################################################

TEMPLATE = app
TARGET = Simple
INCLUDEPATH += .

# Input
SOURCES += simple.cpp
HEADERS += simple.h
QT += widgets
